### ISSUE TITLE
Auto update?

### ISSUE THREAD

**Issue by bobhenl** [Sfiguz7/ExtraTools#6]
## Description (Required)
Hello, could you add auto update? I'm still on ver 14 and there is already 18 out, so it's probably isn't implemented yet?

## Steps to reproduce the Issue (Required)
Install older version of plugin and you see if it updates.

## Expected behavior (Required)
Should update automatically.

## Server Log / Error Report
I found this in log so I discovered that I have old version....
```
[13:17:08] [Server thread/ERROR]: Error occurred while enabling ExtraTools vDEV - 14 (git a330a3dd) (Is it up to date?)
java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/handlers/BlockBreakHandler
	at me.sfiguz7.extratools.ExtraTools.onEnable(ExtraTools.java:38) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.handlers.BlockBreakHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 11 more
```

## Environment (Required)

 - Minecraft Version: 1.16.1
 - CS-CoreLib Version: 88
 - Slimefun Version: 588
 - Plugin Version:  14 (but will update to 18 aswell)

**Comment by Alessio-Colombo** [comment]
Auto update was fixed in ExtraTools #17, the config would never be written anymore so I must have had mistakenly removed it; any version equals or above that should correctly generate the ExtraTools folder containing a 2 line config (a bit sad I know) with the auto update option
